# Generated by Django 4.2.4 on 2023-09-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(verbose_name='Date')),
                ('max_temp', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Max temperature (°C)')),
                ('avg_temp', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Avg temperature (°C)')),
                ('max_wind', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Max wind (kph)')),
                ('avg_humidity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Avh humidity')),
                ('condition', models.CharField(max_length=128, verbose_name='Condition')),
            ],
            options={
                'verbose_name': 'Daily weather forecast',
                'verbose_name_plural': 'Weather forecast',
            },
        ),
    ]
